### ISSUE TITLE
ApiService dosen't run on 1.15

### ISSUE THREAD

**Issue by Pothulapati** [deislabs/smi-metrics#18]
The `v1alpha1.metrics.smi-spec.io` ApiService fails on Kubernetes clusters with verison 1.15 marking as `FailedDiscoveryCheck`

```
  conditions:
  - lastTransitionTime: "2019-06-28T16:20:22Z"
    message: 'failing or missing response from https://10.100.82.130:443: bad status
      from https://10.100.82.130:443: 404'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```

Looks like this has something to do with the the service not exposing the information about it self as the pods and services run successfully.
